### ISSUE TITLE
Explicar sobre o uso do login de root e do sudo

### ISSUE THREAD

**Issue by leandroramos** [kretcheu/dicas#1]
Posso fazer algo a respeito, mas acredito que o mestre tenha muito mais a dizer.

**Comment by kretcheu** [comment]
Olá, a qual artigo/arquivo.md vc se refere?

**Comment by leandroramos** [comment]
Seria a criação de um arquivo novo falando sobre a diferença do uso. Um
novo tópico.

Em ter, 3 de mar de 2020 04:04, kretcheu <notifications@github.com>
escreveu:
