### ISSUE TITLE
Colocar links para os markdowns no README.md

### ISSUE THREAD

**Issue by leandroramos** [kretcheu/dicas#2]
Acredito que assim ficará mais fácil para as pessoas saberem onde clicar.

**Comment by kretcheu** [comment]
A função do README.md é a de dar uma ideia geral do repositório, quando está na aba code, tem link para cada um dos artigos.
Não acha que se colocar no README.md terei que alterar o README.md a cada novo artigo?

**Comment by leandroramos** [comment]
Tem razão.
É que eu estava imaginando isso como se fosse uma Github Page, vou fechar a
issue. Obrigado.

Em ter, 3 de mar de 2020 04:07, kretcheu <notifications@github.com>
escreveu:

**Comment by kretcheu** [comment]
Sim, pretendo em breve fazer uma Github Page ou alguma alternativa.
